pipeline{
    agent any
    parameters{
        strings(name: 'NAME', defaultValue: 'World', description: 'Who are we saying hello to?')
    }
    environment{
        Docker_HUB_CREDENTISALS = credentials('tejal15')
    }

    stages{
        stage('GREETING'){
            steps{
                echo "HELLO, ${params.NAME}!"
            }
        }
        stage('checkout code'){
            steps{
                checkout scm
            }
        }
        stage('instal dependencies'){
            steps{
                sh 'pip install -r requirements.txt'
            }
        }
        stage('run tests'){
            steps{
                sh 'pytest tests/'
            }
            post{
                always{
                    junit 'reports/*.xml'
                }
            }
        }
        stage('build docker image'){
            steps{
                script{
                    sh 'docker build -t $DOCKERHUB_USER/jenkins-flask:latest .'
                }
            }
        }
        stage('run container'){
            steps{
                script{
                    sh 'docker run -d -p 5000:5000 $DOCKERHUB_USER/jenkins-flask:latest'
                    sh 'sleep 5 && curl -f http://localhost:5000/'
                    sh 'docker stop flask_app && docker rm flask_app'
                }
            }
        }
         stage('Push to DockerHub') {
            steps {
                sh 'echo $DOCKERHUB_USER_PSW | docker login -u $DOCKERHUB_USER --password-stdin'
                sh 'docker push $DOCKERHUB_USER/jenkins-flask:latest'
            }
        }
    }
    post {
        always {
            echo "Build finished with status: ${currentBuild.currentResult}"
        }
    }
}
    

