pipeline {
    agent any

    parameters {
        string(name: 'NAME', defaultValue: 'World', description: 'Who are we saying hello to?')
    }

    environment {
        DOCKER_HUB_USER = 'tejal15'
        DOCKER_HUB_PSW  = 'Tejaljoshi@15'
    }

    stages {
        stage('GREETING') {
            steps {
                echo "HELLO, ${params.NAME}!"
            }
        }

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
        steps {
            sh '''
                python3 -m venv venv
                ./venv/bin/pip install --upgrade pip
                ./venv/bin/pip install -r python-jenkins-project/requirements.txt
            '''
        }
    }



        stage('Run Tests') {
            steps {
                sh './venv/bin/pytest python-jenkins-project/Myapp_test.py --junitxml=reports/results.xml'
            }
            post {
                always {
                    junit 'reports/results.xml'
                    }
                }
            }
        }


        stage('Build Docker Image') {
            steps {
                sh "DOCKER_BUILDKIT=0 docker build -t ${DOCKER_HUB_USER}/jenkins-flask:latest python-jenkins-project"
            }
        }


        stage('Run Container') {
            steps {
                sh "docker run -d --name flask_app -p 5000:5000 ${DOCKER_HUB_USER}/jenkins-flask:latest"
                sh "sleep 5 && curl -f http://localhost:5000/"
                sh "docker stop flask_app && docker rm flask_app"
            }
        }

        stage('Push to DockerHub') {
            steps {
                sh "echo ${DOCKER_HUB_PSW} | docker login -u ${DOCKER_HUB_USER} --password-stdin"
                sh "docker push ${DOCKER_HUB_USER}/jenkins-flask:latest"
            }
        }
    }

    post {
        always {
            echo "Build finished with status: ${currentBuild.currentResult}"
        }
    }
}
